import Foundation

struct Word: Identifiable, Codable {
    let id = UUID()
    let german: String
    let russian: String
}

struct Category: Identifiable, Codable {
    let id = UUID()
    let title: String
    let words: [Word]
}

let categories: [Category] = [

    // 1. Время, даты, частота
    Category(title: "Время, даты, частота", words: [
        Word(german: "Genauso", russian: "точно так же, одинаково"),
        Word(german: "Dauern", russian: "длиться, продолжаться"),
        Word(german: "Wann", russian: "когда / если"),
        Word(german: "Vormittag", russian: "до обеда"),
        Word(german: "Nachmittag", russian: "после обеда"),
        Word(german: "Ostern", russian: "Пасха"),
        Word(german: "Zur Zeit", russian: "в данный момент"),
        Word(german: "Jeden", russian: "каждый"),
        Word(german: "Früh", russian: "рано"),
        Word(german: "Voll", russian: "полный"),
        Word(german: "Halb", russian: "половина"),
        Word(german: "Spät", russian: "поздно"),
        Word(german: "Täglich", russian: "ежедневно"),
        Word(german: "Wieder", russian: "снова, опять"),
        Word(german: "Vorher", russian: "до этого"),
        Word(german: "Den ganzen Tag", russian: "весь день"),
        Word(german: "Immer", russian: "всегда"),
        Word(german: "Meistens", russian: "в большинстве случаев"),
        Word(german: "Oft", russian: "часто"),
        Word(german: "Manchmal", russian: "иногда"),
        Word(german: "Selten", russian: "редко"),
        Word(german: "Nie", russian: "никогда")
    ]),

    // 2. Быт, дом, предметы
    Category(title: "Быт, дом, предметы", words: [
        Word(german: "Hausbewohner", russian: "жители дома"),
        Word(german: "bittet dringend", russian: "настойчиво просит"),
        Word(german: "Hausmüll", russian: "бытовой мусор"),
        Word(german: "Zusammen / getrennt", russian: "вместе / раздельно"),
        Word(german: "weiterhin", russian: "по-прежнему"),
        Word(german: "Müll", russian: "мусор"),
        Word(german: "Tonne", russian: "контейнер, бак"),
        Word(german: "nicht vorgesehen", russian: "не предусмотренный"),
        Word(german: "Restmüll", russian: "остаточный мусор"),
        Word(german: "Biotonne", russian: "контейнер для биоотходов"),
        Word(german: "Vergangenheit", russian: "прошлое"),
        Word(german: "Müllabfuhr", russian: "вывоз мусора"),
        Word(german: "Betrieb", russian: "предприятие"),
        Word(german: "Beschwerde", russian: "жалоба"),
        Word(german: "Hausmeister", russian: "дворник, завхоз"),
        Word(german: "die Couch", russian: "диван"),
        Word(german: "der Rasen", russian: "газон"),
        Word(german: "Die Gießkanne", russian: "лейка"),
        Word(german: "Spielsachen", russian: "игрушки"),
        Word(german: "Naja", russian: "ну, такое..."),
        Word(german: "Ziehen", russian: "переезжать"),
        Word(german: "Umzug", russian: "переезд"),
        Word(german: "die Sachen", russian: "вещи"),
        Word(german: "die Kleidung", russian: "одежда"),
        Word(german: "Kuchen", russian: "пирог"),
        Word(german: "Herd", russian: "плита"),
        Word(german: "Teller", russian: "тарелка"),
        Word(german: "Tassen", russian: "чашки"),
        Word(german: "die Gabel", russian: "вилка"),
        Word(german: "der Löffel", russian: "ложка"),
        Word(german: "Besteck", russian: "столовые приборы"),
        Word(german: "Sofa", russian: "диван"),
        Word(german: "Sessel", russian: "кресло"),
        Word(german: "Decken", russian: "одеяла"),
        Word(german: "Küchentisch", russian: "кухонный стол"),
        Word(german: "Wasseruhr", russian: "водяной счётчик"),
        Word(german: "Hausverwaltung", russian: "домоуправление"),
        Word(german: "Wand", russian: "стена"),
        Word(german: "Fensterbank", russian: "подоконник"),
        Word(german: "Vorhang", russian: "штора, занавеска")
    ]),

    // 3. Транспорт и направления
    Category(title: "Транспорт и направления", words: [
        Word(german: "leihen", russian: "одалживать, брать напрокат"),
        Word(german: "besichtigen", russian: "осматривать"),
        Word(german: "Hintergrund", russian: "сзади"),
        Word(german: "Vordergrund", russian: "спереди"),
        Word(german: "in", russian: "внутри"),
        Word(german: "am", russian: "у / на точке"),
        Word(german: "nach", russian: "в направлении (город, страна, домой)"),
        Word(german: "zu / zum / zur", russian: "к объекту или человеку"),
        Word(german: "Da drüben ist einer", russian: "там есть один"),
        Word(german: "nah", russian: "близко"),
        Word(german: "Nähe", russian: "поблизости"),
        Word(german: "näher", russian: "ближе"),
        Word(german: "am nächsten", russian: "самый близкий"),
        Word(german: "näher als", russian: "ближе, чем"),
        Word(german: "Drehen", russian: "крутить, поворачивать"),
        Word(german: "Wenig", russian: "мало"),
        Word(german: "Einfach", russian: "простой, лёгкий"),
        Word(german: "Schwierig", russian: "трудный"),
        Word(german: "Weit", russian: "далеко, широкий"),
        Word(german: "Einsteigen", russian: "садиться в транспорт"),
        Word(german: "Umsteigen", russian: "пересаживаться"),
        Word(german: "Aussteigen", russian: "выходить из транспорта"),
        Word(german: "Steigen", russian: "подниматься, садиться в транспорт"),
        Word(german: "Eingang", russian: "вход"),
        Word(german: "Ausgang", russian: "выход"),
        Word(german: "Haupteingang", russian: "главный вход"),
        Word(german: "Seiteneingang", russian: "боковой вход"),
        Word(german: "Flughafen", russian: "аэропорт"),
        Word(german: "Verkehrsmittel", russian: "транспортное средство"),
        Word(german: "Abfahrt", russian: "отправление"),
        Word(german: "Beim", russian: "у, при, во время"),
        Word(german: "Dort", russian: "там"),
        Word(german: "Da", russian: "тут, вот"),
        Word(german: "Zurück", russian: "назад"),
        Word(german: "Am Stadtrand", russian: "на окраине")
    ]),

    // 4. Погода и природа
    Category(title: "Погода и природа", words: [
        Word(german: "Es schneit", russian: "идёт снег"),
        Word(german: "Es regnet", russian: "идёт дождь"),
        Word(german: "Es ist neblig", russian: "туманно"),
        Word(german: "Es ist heiß", russian: "жарко"),
        Word(german: "Es ist kalt", russian: "холодно"),
        Word(german: "Es ist warm", russian: "тепло"),
        Word(german: "Es ist sonnig", russian: "солнечно"),
        Word(german: "Es ist bewölkt", russian: "облачно"),
        Word(german: "Es ist windig", russian: "ветрено"),
        Word(german: "Es donnert", russian: "гремит гром"),
        Word(german: "Es blitzt", russian: "сверкает молния"),
        Word(german: "Der Himmel ist klar", russian: "небо ясное"),
        Word(german: "Frühling", russian: "весна"),
        Word(german: "Sommer", russian: "лето"),
        Word(german: "Herbst", russian: "осень"),
        Word(german: "Winter", russian: "зима"),
        Word(german: "Der Norden", russian: "север"),
        Word(german: "Der Süden", russian: "юг"),
        Word(german: "Der Westen", russian: "запад"),
        Word(german: "Der Osten", russian: "восток"),
        Word(german: "Der Baum", russian: "дерево"),
        Word(german: "Die Blume", russian: "цветок"),
        Word(german: "Das Blatt", russian: "лист"),
        Word(german: "Das Gras", russian: "трава"),
        Word(german: "Der Wald", russian: "лес"),
        Word(german: "Der Berg", russian: "гора"),
        Word(german: "Der Fluss", russian: "река"),
        Word(german: "Der See", russian: "озеро"),
        Word(german: "Das Meer", russian: "море"),
        Word(german: "Der Himmel", russian: "небо"),
        Word(german: "Der Regenbogen", russian: "радуга"),
        Word(german: "Der Schnee", russian: "снег")
    ]),

    // 5. Еда и напитки
    Category(title: "Еда и напитки", words: [
        Word(german: "Fleisch", russian: "мясо"),
        Word(german: "Schmeckt", russian: "вкусно")
    ]),

    // 6. Тело и здоровье
    Category(title: "Тело и здоровье", words: [
        Word(german: "Wanduhr", russian: "настенные часы"),
        Word(german: "Handuhr", russian: "наручные часы"),
        Word(german: "Kopf", russian: "голова"),
        Word(german: "Stirn", russian: "лоб"),
        Word(german: "Schläfe", russian: "висок"),
        Word(german: "Auge", russian: "глаз"),
        Word(german: "Nase", russian: "нос"),
        Word(german: "Ohr", russian: "ухо"),
        Word(german: "Mund", russian: "рот"),
        Word(german: "Lippe", russian: "губа"),
        Word(german: "Zahn", russian: "зуб"),
        Word(german: "Zähne", russian: "зубы"),
        Word(german: "Zunge", russian: "язык"),
        Word(german: "Hals", russian: "шея, горло"),
        Word(german: "Schulter", russian: "плечо"),
        Word(german: "Rücken", russian: "спина"),
        Word(german: "Brust", russian: "грудь"),
        Word(german: "Bauch", russian: "живот"),
        Word(german: "Ellbogen", russian: "локоть"),
        Word(german: "Arm", russian: "рука"),
        Word(german: "Hand", russian: "кисть руки"),
        Word(german: "Finger", russian: "палец руки"),
        Word(german: "Zehe", russian: "палец ноги"),
        Word(german: "Bein", russian: "нога"),
        Word(german: "Oberschenkel", russian: "бедро"),
        Word(german: "Knie", russian: "колено"),
        Word(german: "Fuß", russian: "стопа"),
        Word(german: "Blut", russian: "кровь"),
        Word(german: "Knochen", russian: "кость"),
        Word(german: "Muskel", russian: "мышца")
    ]),

    // 7. Чувства и эмоции
    Category(title: "Чувства и эмоции", words: [
        Word(german: "Fehlt", russian: "отсутствует / не хватает"),
        Word(german: "Hoffe", russian: "надеюсь"),
        Word(german: "lächeln", russian: "улыбаться"),
        Word(german: "Glücklich", russian: "счастливый"),
        Word(german: "Angenehm", russian: "приятно"),
        Word(german: "Sehr erfreut", russian: "очень приятно"),
        Word(german: "Gern", russian: "охотно"),
        Word(german: "Egal", russian: "всё равно"),
        Word(german: "Wunderbar", russian: "прекрасно"),
        Word(german: "Schade", russian: "жаль"),
        Word(german: "Lustig", russian: "весёлый"),
        Word(german: "Traurig", russian: "грустный"),
        Word(german: "Fröhlich", russian: "радостный")
    ]),

    // 8. Прилагательные
    Category(title: "Прилагательные и описания", words: [
        Word(german: "überhaupt", russian: "вообще"),
        Word(german: "Kostenlos", russian: "бесплатно"),
        Word(german: "Sonst", russian: "иначе"),
        Word(german: "Ander", russian: "другой"),
        Word(german: "Fertig", russian: "готово"),
        Word(german: "Nicht viele", russian: "немного"),
        Word(german: "Warm", russian: "тёплый"),
        Word(german: "Hell", russian: "светлый"),
        Word(german: "Dunkel", russian: "тёмный"),
        Word(german: "Schön", russian: "красивый"),
        Word(german: "Hässlich", russian: "уродливый"),
        Word(german: "Lang", russian: "длинный"),
        Word(german: "Kurz", russian: "короткий"),
        Word(german: "Gut", russian: "хороший"),
        Word(german: "Schlecht", russian: "плохой"),
        Word(german: "Stark", russian: "сильный"),
        Word(german: "Schwach", russian: "слабый"),
        Word(german: "Richtig", russian: "правильный"),
        Word(german: "Falsch", russian: "неправильный"),
        Word(german: "Teuer", russian: "дорогой"),
        Word(german: "Günstig", russian: "дешёвый")
    ]),

    // 9. Глаголы
    Category(title: "Глаголы (действия)", words: [
        Word(german: "Vergessen", russian: "забывать"),
        Word(german: "Bedeutet", russian: "значит"),
        Word(german: "Wiederholen", russian: "повторять"),
        Word(german: "Dafür", russian: "для этого"),
        Word(german: "Beantragen", russian: "подавать заявление"),
        Word(german: "Anschluss", russian: "стыковка, пересадка"),
        Word(german: "Verspätung", russian: "опоздание"),
        Word(german: "Verpassen", russian: "пропускать"),
        Word(german: "Dürfen", russian: "иметь разрешение"),
        Word(german: "Treffen", russian: "встречаться"),
        Word(german: "Einladen", russian: "приглашать"),
        Word(german: "Gerade", russian: "сейчас, только что"),
        Word(german: "Kennen", russian: "знать"),
        Word(german: "Schicken", russian: "отправлять"),
        Word(german: "Gleich", russian: "сейчас, скоро"),
        Word(german: "Übung", russian: "упражнение"),
        Word(german: "Erklären", russian: "объяснять"),
        Word(german: "Nehmen", russian: "брать"),
        Word(german: "Schwimmen", russian: "плавать"),
        Word(german: "Können", russian: "мочь"),
        Word(german: "Tragen", russian: "носить"),
        Word(german: "Bleiben", russian: "оставаться"),
        Word(german: "Anrufen", russian: "звонить"),
        Word(german: "Holen", russian: "забирать"),
        Word(german: "Halten", russian: "держать"),
        Word(german: "Zahlen", russian: "платить"),
        Word(german: "Bestellen", russian: "заказывать"),
        Word(german: "Bekommen", russian: "получать"),
        Word(german: "Benutzen", russian: "использовать"),
        Word(german: "Bringen", russian: "приносить"),
        Word(german: "Mitbringen", russian: "приносить с собой"),
        Word(german: "Putzen", russian: "чистить"),
        Word(german: "Schlafen", russian: "спать"),
        Word(german: "Stehen", russian: "стоять"),
        Word(german: "Servieren", russian: "обслуживать"),
        Word(german: "Pflegen", russian: "заботиться"),
        Word(german: "Reparieren", russian: "ремонтировать"),
        Word(german: "Korrigieren", russian: "исправлять"),
        Word(german: "Arbeiten", russian: "работать"),
        Word(german: "Wählen", russian: "выбирать"),
        Word(german: "Streichen", russian: "зачёркивать / красить"),
        Word(german: "Besuchen", russian: "посещать"),
        Word(german: "Abholen", russian: "забирать"),
        Word(german: "Umtauschen", russian: "обменивать"),
        Word(german: "Reden", russian: "говорить"),
        Word(german: "Lachen", russian: "смеяться"),
        Word(german: "Tanzen", russian: "танцевать"),
        Word(german: "Schauen", russian: "смотреть")
    ]),

    // 10. Служебные слова
    Category(title: "Служебные слова, союзы, предлоги", words: [
        Word(german: "Deshalb", russian: "поэтому"),
        Word(german: "Leider", russian: "к сожалению"),
        Word(german: "Mindestens", russian: "минимум"),
        Word(german: "Unbedingt", russian: "обязательно"),
        Word(german: "Vielleicht", russian: "возможно"),
        Word(german: "Ohne", russian: "без"),
        Word(german: "Etwas", russian: "что-то"),
        Word(german: "Direkt", russian: "прямо"),
        Word(german: "Also", russian: "значит"),
        Word(german: "Vor", russian: "перед"),
        Word(german: "Nach", russian: "после"),
        Word(german: "Unter", russian: "под"),
        Word(german: "Über", russian: "над"),
        Word(german: "Neben", russian: "рядом"),
        Word(german: "Zwischen", russian: "между"),
        Word(german: "Auf", russian: "на"),
        Word(german: "Am", russian: "у")
    ]),

    // 11. Инструменты и работа
    Category(title: "Инструменты и работа", words: [
        Word(german: "sorgfältig", russian: "тщательно"),
        Word(german: "zum Beispiel", russian: "например"),
        Word(german: "die Treppe", russian: "лестница"),
        Word(german: "Der Haken", russian: "крючок"),
        Word(german: "Der Korb", russian: "корзина"),
        Word(german: "Die Schublade", russian: "ящик"),
        Word(german: "Der Boden", russian: "пол, земля"),
        Word(german: "die Decke", russian: "потолок"),
        Word(german: "Ordnung", russian: "порядок"),
        Word(german: "Stellen", russian: "ставить"),
        Word(german: "Legen", russian: "класть"),
        Word(german: "Hängen", russian: "висеть"),
        Word(german: "die Ecke", russian: "угол"),
        Word(german: "Zuletzt", russian: "в последний раз"),
        Word(german: "Zuerst", russian: "сначала"),
        Word(german: "Cuttermesser", russian: "канцелярский нож"),
        Word(german: "Messer", russian: "нож"),
        Word(german: "Hammer", russian: "молоток"),
        Word(german: "Zange", russian: "плоскогубцы"),
        Word(german: "Rohrzange", russian: "газовый ключ"),
        Word(german: "Winkelschleifer", russian: "болгарка"),
        Word(german: "Bohrmaschine", russian: "дрель"),
        Word(german: "Bohrer", russian: "сверло"),
        Word(german: "Drahtbürste", russian: "щётка по металлу"),
        Word(german: "Verlängerungskabel", russian: "удлинитель"),
        Word(german: "Schweißgerät", russian: "сварочный аппарат"),
        Word(german: "Malerkrepp", russian: "малярный скотч"),
        Word(german: "Lappen", russian: "ветошь"),
        Word(german: "Eimer", russian: "ведро")
    ]),

    // 12. Продукты и IT
    Category(title: "Продукты и IT", words: [
        Word(german: "Zuzüglich", russian: "плюс, сверх того"),
        Word(german: "Zusätzlich", russian: "дополнительно"),
        Word(german: "eine Nachricht", russian: "сообщение"),
        Word(german: "schreiben", russian: "писать"),
        Word(german: "löschen", russian: "удалять"),
        Word(german: "chatten", russian: "переписываться"),
        Word(german: "eine E-Mail", russian: "электронное письмо"),
        Word(german: "lesen", russian: "читать"),
        Word(german: "abschicken", russian: "отправлять"),
        Word(german: "schalten", russian: "переключать"),
        Word(german: "den Computer", russian: "компьютер"),
        Word(german: "ausschalten", russian: "выключать"),
        Word(german: "speichern", russian: "сохранять"),
        Word(german: "reparieren", russian: "чинить"),
        Word(german: "im Internet", russian: "в интернете"),
        Word(german: "googeln", russian: "искать в Google"),
        Word(german: "surfen", russian: "бродить по интернету"),
        Word(german: "drucken", russian: "печатать"),
        Word(german: "eine Zeitungsanzeige", russian: "газетное объявление"),
        Word(german: "herunterladen", russian: "скачивать")
    ]),

    // 13. Этажи
    Category(title: "Немецкие этажи", words: [
        Word(german: "KG (Kellergeschoss)", russian: "подвал"),
        Word(german: "EG (Erdgeschoss)", russian: "1 этаж"),
        Word(german: "1. OG", russian: "2 этаж"),
        Word(german: "2. OG", russian: "3 этаж"),
        Word(german: "DG (Dachgeschoss)", russian: "мансарда")
    ]),

    // 14. Учреждения
    Category(title: "Учреждения и документы", words: [
        Word(german: "Einwohnermeldeamt", russian: "регистрация жителей"),
        Word(german: "An- und Abmeldung", russian: "регистрация / снятие"),
        Word(german: "Personalausweis", russian: "удостоверение личности"),
        Word(german: "Reisepass", russian: "загранпаспорт"),
        Word(german: "Parkausweis", russian: "разрешение на парковку"),
        Word(german: "Kfz-Zulassungsstelle", russian: "отдел регистрации ТС"),
        Word(german: "Fahrzeug anmelden/abmelden", russian: "зарегистрировать/снять с учёта"),
        Word(german: "Standesamt", russian: "ЗАГС"),
        Word(german: "Eheschließung", russian: "заключение брака"),
        Word(german: "Geburt melden", russian: "регистрация рождения"),
        Word(german: "Geburtsurkunde", russian: "свидетельство о рождении"),
        Word(german: "Heiratsurkunde", russian: "свидетельство о браке"),
        Word(german: "Agentur für Arbeit", russian: "биржа труда"),
        Word(german: "Arbeitsplatz finden", russian: "найти рабочее место"),
        Word(german: "Ausbildungsplatz finden", russian: "место для обучения"),
        Word(german: "Berufsberatung", russian: "профориентация"),
        Word(german: "Arbeitslosengeld", russian: "пособие по безработице"),
        Word(german: "Kindergeld", russian: "пособие на ребёнка"),
        Word(german: "Ausländerbehörde", russian: "ведомство по делам иностранцев"),
        Word(german: "Familiennachzug", russian: "воссоединение семьи"),
        Word(german: "Aufenthalt", russian: "пребывание"),
        Word(german: "Aufenthaltserlaubnis", russian: "разрешение на пребывание"),
        Word(german: "Integration", russian: "интеграция"),
        Word(german: "Integrationskurs", russian: "интеграционный курс"),
        Word(german: "Orientierungskurs", russian: "курс адаптации")
    ])
]
